# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(472, 422)
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 120, 441, 281))
        self.listWidget.setObjectName("listWidget")
        self.Title = QtWidgets.QLineEdit(parent=Form)
        self.Title.setGeometry(QtCore.QRect(30, 80, 151, 21))
        self.Title.setObjectName("Title")
        self.searchButton = QtWidgets.QPushButton(parent=Form)
        self.searchButton.setGeometry(QtCore.QRect(230, 20, 131, 81))
        self.searchButton.setObjectName("searchButton")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 30, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Каталог библиотеки"))
        self.searchButton.setText(_translate("Form", "Искать"))
        self.comboBox.setItemText(0, _translate("Form", "Автор"))
        self.comboBox.setItemText(1, _translate("Form", "Название"))
